### PR TITLE
update chapter 4

### PR DESCRIPTION
**Pull request by zkamvar**
I've updated content in chapter 4 to clarify wording and update status of the workbench.

One of the things I'm struggling with is the fact that the objectives for the
episode are explicitly about the styles template, but the episode itself seems
to be split between a crash course of collaborating on github and the structure
of lessons.

This is currently a WIP and I should complete it by Monday.

### CODE REVIEW

**Review by vinisalazar — APPROVED** [review]
Thanks @zkamvar, LGTM.

**Comment by vinisalazar** [comment]
Let me know when you're done and I'll review it again.

**Comment by zkamvar** [comment]
Thank you! I won't complete this until tomorrow. I got tied up working on the lesson transition today

**Comment by ErinBecker** [comment]
I was just coming here to review and see that Vini already did so 😆. I read through what is in the draft PR so far and like the changes. @vinisalazar - please go ahead and merge Zhian's changes after your review of the complete version.

**Comment by zkamvar** [comment]
Update: after needed rest, I will update this today sorry for the delay

**Comment by zkamvar** [comment]
It should be ready for review now @vinisalazar

**Review by vinisalazar — APPROVED** [review]
Thank you @zkamvar. I had never used the "Fetch and merge" button myself (usually do everything from the CLI) and I'm teaching this at the Onboarding, so these changes are very welcome!

**Pull request merged**
