### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by katrinleinweber**

### CODE REVIEW

**Comment by remram44** [comment]
Duplicate of #10

**Comment by katrinleinweber** [comment]
Not really, because this PR leaves the white-spaces. I gathered from other Carpentries repos, that auto-whitespace removal is not used.

However, since there are no [`.editorconfig` files](http://obem.be/2015/06/01/a-quick-note-on-editorconfig.html), it's unclear whether all the trailing whitespaces are merely results of not activating any in-editor linting, or whether it was an intentional choice.

**Comment by ErinBecker** [comment]
Thanks for your contribution @katrinleinweber. I've merged @remram44's PR already, so will close this one. The trailing whitespaces were just my mistake.

**Comment by katrinleinweber** [comment]
Would an `.editorconfig` make sense? I'm not sure though, whether if RStudio supports it, yet. Even if not, it might be more convenient in the long-run, than asking contributors to set a specific combination of check-boxes in their editors.

**Comment by remram44** [comment]
My own editor doesn't support it, and there are very few configuration options for Markdown anyway (probably only trailing whitespace... maybe word-wrapping?)

I also suspect a lot of editing across the lessons happens from the GitHub editor.

I tend to not make changes in the formatting, but here I already had changes in every chapter, so I assumed it would be okay. I made it a separate commit for convenience if I was wrong.

**Pull request closed without merging**
